### ISSUE TITLE
Proposal: More conventional Mix task names

### ISSUE THREAD

**Issue by zachallaun** [mimiquate/blend#28]
Hi there! Thanks for making this library available. It's a clever solution to a real problem for library authors. 

---

I have a couple suggestions for renames of the Mix tasks based on what I believe is the current convention:

- `blend.init -> blend.install` - `*.install` has a good amount of traction and will also be run automatically by [Igniter](https://hexdocs.pm/igniter/readme.html) if it is used to add Blend to a project.
- `blend.premix -> blend.gen.premix` - including the `gen` makes it clear that this is generating a file (lots of precedent for this) and not some other kind of side-effecting command.

**Comment by grzuy** [comment]
Hi @zachallaun ,

Thanks for your feedback.

Your suggestions make sense to me.

**Comment by grzuy** [comment]
released in `v0.4.1`
